name: ${PREFIX:-tsfga}
networks:
  default:
    external: false
    name: ${PREFIX:-tsfga}
services:
  postgres:
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    container_name: ${PREFIX:-tsfga}-postgres
    environment:
      PGDATA: "/var/lib/postgresql/18/docker"
      PGHOST: "/var/run/postgresql"
      PGUSER: "${POSTGRES_USER:-dev}"
      POSTGRES_DB: "${POSTGRES_DB:-dev}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_USER: "${POSTGRES_USER:-dev}"
      TZ: "America/Sao_Paulo"
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      timeout: 10s
    image: postgres:18-alpine@sha256:035b9ab53cfa147d7202b61f5f7782b939ae815b7d6bc81c96b7b42ff1fca950
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker
      - ./infra/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./infra/postgresql/init-openfga-schema.sql:/docker-entrypoint-initdb.d/init-openfga-schema.sql:ro

  openfga-migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:latest@sha256:abddf9ce5e0770e6fcbcfdc44e6539bb629a1ab1d77761324db12dbea5539d27
    container_name: ${PREFIX:-tsfga}-openfga-migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://${POSTGRES_USER:-dev}:${POSTGRES_PASSWORD:-password}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-dev}?sslmode=disable&search_path=openfga
    command: migrate
    networks:
      - default

  openfga:
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest@sha256:abddf9ce5e0770e6fcbcfdc44e6539bb629a1ab1d77761324db12dbea5539d27
    container_name: ${PREFIX:-tsfga}-openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://${POSTGRES_USER:-dev}:${POSTGRES_PASSWORD:-password}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-dev}?sslmode=disable&search_path=openfga
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100 #see postgres container
      - OPENFGA_PLAYGROUND_ENABLED=true
    networks:
      - default
    ports:
      - "8080:8080" #http
      - "8081:8081" #grpc
      - "3000:3000" #playground
      - "2112:2112" #prometheus metrics
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/grpc_health_probe",
          "-addr=openfga:8081"
        ]
      interval: 5s
      timeout: 30s
      retries: 3

volumes:
  postgres-data:
    driver: local
    name: ${PREFIX:-tsfga}-postgres-data
